// types/storylines.ts
export interface Story {
    book: number;
    title: string;
    tagline: string;
    id: number;
    header: string;
    content: string;
    imageUrl: string;
    funFact: string;
  }
  
  // storylines.ts
export const stories: Story[] = [
    {
      book: 1,
      title: "Snappy and the Nuts",
      tagline: "Snappy needs to save nuts for winter.",
      id: 10,
      header: "Snappy and the Nuts",
      content: "Snappy was a busy, happy squirrel. All day long in the fall he searched through the leaves on the forest floor for tasty nuts to store for the long winter. He squeaked with excitement each time he found a nut and quickly buried it where he was sure he'd find it in the coming months. He had to hide them because other animals wanted to eat them, too.",
      imageUrl: "1/0.png",
      funFact: "What kinds of valuable things do you like to save? Money? Items to trade?",
    },
    {
      book: 1,
      title: "",
      tagline: "",
      id: 11,
      header: "The Nuts",
      content: "Sometimes the Deer brothers trampled them and broke the nut shells. Often the naughty Chipmunk family stole them. Sometimes, Snappy couldn't quite remember where he put the piles of nuts. Snappy had been working for a long time and had saved many nuts. They would taste so good all winter when the ground is covered with snow.",
      imageUrl: "1/1.png",
      funFact: "Where do you store your valuable things? How do you make sure they are safe?",
    },
    {
      book: 1,
      title: "",
      tagline: "",
      id: 12,
      header: "Auntie Pip",
      content: "Snappy thought for a long time about the best place to store them safely where no one could break or steal the nuts. Finally he smiled happily, thinking: \"I'll ask Auntie Pip. She knows all kinds of interesting things.\"",
      imageUrl: "1/2.png",
      funFact: "Whom do you ask about important money matters?",
    },
    {
      book: 1,
      title: "",
      tagline: "",
      id: 13,
      header: "A Safe Box",
      content: "Auntie Pip told Snappy that the forest has lots of good places to store his property.  \"If you want them back within the next year or so, they\'ll have to be where we can find them easily but will be held safe from other Forest creatures.  I\'d suggest Owl\'s Forest Bank.  You can put them in his safe box where he can watch it all the time.  Lots of animals store their things with Owl. He is awake all night and during the day he has several salamanders who watch what is held in the bank.\"",
      imageUrl: "1/3.png",
      funFact: "Where do you store your valuable things? How do you make sure they are safe? Have you ever seen a bank\'s safe deposit box area?",
    },
    {
      book: 1,
      title: "",
      tagline: "",
      id: 14,
      header: "Mr. Fox",
      content: "Mr. Fox, who always seemed interested in other peoples’ business, ambled over to Snappy and Auntie Pip. “I have a bank as well, much better than Owl’s. It’s called ‘Fox’s Friends’ Bank’. I will give you three pine nuts for every acorn that you deposit in my bank.”",
      imageUrl: "1/4.png",
      funFact: "What are the names of your local banks?",
    },
    {
      book: 1,
      title: "",
      tagline: "",
      id: 15,
      header: "A Sharp Customer",
      content: "Auntie Pip looked severely at Fox. “Mr. Fox, I know very well that you make this offer to everyone. I also know that you will not allow Snappy to take his nuts back until a whole year has passed. And you say you give more pine nuts, but you won’t let Snappy have those either until the year has passed. It’s not quite fair.”",
      imageUrl: "1/5.png",
      funFact: "Are there banks in your town or city that seem to offer more to their customers, but really offer less?",
    },
    {
      book: 1,
      title: "",
      tagline: "",
      id: 16,
      header: "A Better Bank",
      content: "Mr. Fox walked away in a huff. Auntie Pip looked kindly at Snappy. “Many banks want you to deposit your property with them so that they can use it to buy other things, but you have to be careful. Owl is a good banker and won’t take advantage of you. He will give you only two pine nuts for each acorn, but you can get your acorns back any time and you get your pine nuts right away.”",
      imageUrl: "1/6.png",
      funFact: "What other kinds of business practices would a bank offer to attract customers?",
    },
    {
      book: 1,
      title: "",
      tagline: "",
      id: 17,
      header: "A Deposit",
      content: "Snappy thought that this sounded like a great plan. He worked hard all day digging up his nuts and carrying them to Owl’s Bank. Finally he had a large pile of nuts ready for Owl to take, and knocked at the bank’s door in Owl’s big tree stump. Owl put on his spectacles and turned his head this way and that to look at the beautiful pile of nuts. “You’re welcome to store these nuts in my bank, Snappy,” said Owl, “but you’ll need to open an account.”",
      imageUrl: "1/7.png",
      funFact: "When is your local bank open?",
    },
    {
      book: 1,
      title: "",
      tagline: "",
      id: 18,
      header: "Safe",
      content: "Snappy wrote his name on the leaf that Owl showed him.  Owl accepted it and signed it carefully. Together with Aunt Pip, Snappy and Owl carried the nuts to a safe storeroom in the base of Owl’s tree stump. “Now,” Snappy thought, “my property is safe from the Chipmunks and the Deer brothers - and Mr. Fox as well!”",
      imageUrl: "1/8.png",
      funFact: "Do you own a bank account? Why or Why not? What are your goals?",
    },
    {
      book: 2,
      title: "Snappy Needs a Nest",
      tagline: "Snappy needs a warm home!",
      id: 20,
      header: "Snappy Needs a Nest",
      content: "One morning, Snappy Squirrel looked out from under his flimsy shelter of leaves and twigs and saw that the ground was covered with white frost. Snowflakes gently drifted down from the sky and the ground felt hard and cold to the touch. Winter was coming, and Snappy knew that his small shelter was not warm enough or high enough to be safe from other animals and the cold winds. If he could buy a nest, he'd be much warmer and happier.  But nests are very expensive.",
      imageUrl: "2/0.png",
      funFact: "Why do you think Snappy’s flimsy shelter isn’t safe enough for the winter?",
    },
    {
      book: 2,
      title: "Snappy Needs a Nest",
      tagline: "Snappy needs a warm home!",
      id: 21,
      header: "A consultation",
      content: "Snappy went to Auntie Pip's cozy nest made of finest oak leaves. He relaxed in the warmth and asked his Auntie how many nuts and seeds he would need to buy his own nest.  “You need to save as many nuts as you can gather,” said Auntie Pip. “Don’t eat them right when you find them, but eat one and save ten.”",
      imageUrl: "",
      funFact: "If you got $10 for your allowance, do you think you could save $9 and only spend $1? Why or why not?",
    },
    {
      book: 2,
      title: "Snappy Needs a Nest",
      tagline: "Snappy needs a warm home!",
      id: 22,
      header: "Earning interest",
      content: "Snappy already has stored many nuts with Owl’s Forest Bank and is earning interest on them when Owl gives him seeds in return for the nuts. But Auntie Pip says that he can save still more, “If you make a plan to only eat a small portion of the nuts you find and store the rest for the future, you will own more nuts, earn more interest, and you’ll be able to buy a nest soon. You must save for the future,” said Auntie, smiling and looking at the walls of her own snug nest.",
      imageUrl: "",
      funFact: "Why do you think saving money in a bank is a good idea instead of spending it all right away?",
    },
    {
      book: 2,
      title: "Snappy Needs a Nest",
      tagline: "Snappy needs a warm home!",
      id: 23,
      header: "Enough interest?",
      content: "But Snappy knows that although Owl's Bank is safe place to store his valuables, he still only gets two small seeds for each nut that he deposits in the bank. Worried, he thinks that by getting only two seeds for each nut, it will take years to add up enough for pay for a nest. Snappy asks, \"Is there any place else I could put my nuts to earn more seeds, so that I can earn more seeds more quickly?\"",
      imageUrl: "",
      funFact: "If you wanted to save up for something big, like a bike or a toy, would you look for a way to make your money grow faster? How?",
    },
    {
      book: 2,
      title: "Snappy Needs a Nest",
      tagline: "Snappy needs a warm home!",
      id: 24,
      header: "Investing in a business",
      content: "Auntie Pip says he could use some of his nuts to buy part of the Deer Brothers’ Lawn Service.  They take care of lawns, like keeping the grass cut, pushing leaves off of the trails, and trampling down snow, but they need to buy some tools to make their business work better.",
      imageUrl: "",
      funFact: "What do you think would happen if a company didn’t have the tools or workers it needed to grow?",
    },
    {
      book: 2,
      title: "Snappy Needs a Nest",
      tagline: "Snappy needs a warm home!",
      id: 25,
      header: "The Deer Brothers' Lawn Service",
      content: "The Deer Brothers are willing to sell a little part of their business to interested buyers. Giving the Brothers nuts now, or investing in their business, will help them grow their business by buying tools and hiring more workers, and will help them to give the investor bigger returns in the future.  Aunt Pip tells him, \"Why not buy a share of their business?\"",
      imageUrl: "",
      funFact: "Would you want to own part of a company if it meant you could earn extra money each year? Why or why not?",
    },
    {
      book: 2,
      title: "Snappy Needs a Nest",
      tagline: "Snappy needs a warm home!",
      id: 26,
      header: "Sharing a business",
      content: "Snappy thinks that sharing a business, especially one he doesn't run himself, sounds great. Auntie Pip provides more information, “These shares in the company are called 'common stocks' because anybody can buy them.\" A share of the Deer Brothers\' business is one nut of the business\'s profit. Snappy learns that he can buy a share of this company for only ten nuts.",
      imageUrl: "",
      funFact: "Would you prefer to run your own company or invest in someone else's?",
    },
    {
      book: 2,
      title: "Snappy Needs a Nest",
      tagline: "Snappy needs a warm home!",
      id: 27,
      header: "Dividends",
      content: "Delighted, Snappy learns that every owner of the company gets a few seeds at the end of the year when the company is successful and has nuts left over after paying expenses and making sure the Brothers themselves are well paid.  These seeds are called a 'dividend' and the more of the company Snappy owns, the more dividends he gets as long as the company does good business. That sounds like a very nice arrangement to Snappy.",
      imageUrl: "",
      funFact: "If something you bought for $10 could be sold to someone else for $11, would you sell it? Why or why not?",
    },
    {
      book: 2,
      title: "Snappy Needs a Nest",
      tagline: "Snappy needs a warm home!",
      id: 28,
      header: "Taxes",
      content: "Auntie Pip reminds him that Big Bear, who runs the whole forest and keeps everything in order, takes a little of the dividend each year, which he calls 'taxes'.  Snappy frowns a little when he hears this, but he understands that the Big Bear has expenses of his own like keeping the chipmunks in line and making sure that Skunk’s Perfume company doesn’t poison anyone. But Snappy is still relieved that he gets to keep most of the dividend.",
      imageUrl: "",
      funFact: "Do you think it\'s fair that we pay taxes to the government? What do you think the government uses that money for?",
    },
    {
      book: 2,
      title: "Snappy Needs a Nest",
      tagline: "Snappy needs a warm home!",
      id: 29,
      header: "Making progress",
      content: "Several months pass. The Deer Brothers, with their new tools and hard workers, have a booming business trimming paths and getting the forest ready for Spring.  Snappy realizes that their Lawn Service company is making so much profit and paying out such regular dividends that each share in the company that he bought for ten nuts each is now selling for eleven nuts each.  Snappy could sell the shares that he bought for ten nuts to the other squirrels for eleven nuts, giving him one nut that he didn't have before and he didn't have to go out and find.",
      imageUrl: "",
      funFact: "Where can you find information about stock prices?",
    },
    {
      book: 2,
      title: "Snappy Needs a Nest",
      tagline: "Snappy needs a warm home!",
      id: 210,
      header: "Active saving",
      content: "Of course, Big Bear who runs the Forest has to be paid part of the profit Snappy made from buying and selling, but Snappy still gets to keep most of it. Snappy is kept busy running back and forth between the Deer Brothers and Owl's Bank, storing more and more nuts and thinking of the beautiful nest that he will be able to buy very soon.",
      imageUrl: "",
      funFact: "If you owned part of a company, would you sell it now to get quick money or keep it to earn more later? Why?",
    },
    {
      book: 3,
      title: "Snappy Plays the Stock Market",
      tagline: "Snappy loses some and wins some",
      id: 30,
      header: "Snappy Plays the Stock Market",
      content: "Snappy was very pleased with his successful investment in the Deer Brothers’ Lawn Service. He had begun to make a name for himself amongst the other forest creatures as an up-and-coming young squirrel!",
      imageUrl: "3/0.png",
      funFact: "How can making smart financial decisions impact your reputation and opportunities for the future?",
    },
    {
      book: 3,
      title: "Snappy Plays the Stock Market",
      tagline: "Snappy loses some and wins some",
      id: 31,
      header: "Snappy Plays the Stock Market",
      content: "Thinking that there might be other companies with as good profits as those earned by the Deer Brothers, he decided to consult with Auntie Pip about other opportunities in the forest.",
      imageUrl: "",
      funFact: "Why is it important to explore multiple opportunities before making an investment?",
    },
    {
      book: 3,
      title: "Snappy Plays the Stock Market",
      tagline: "Snappy loses some and wins some",
      id: 32,
      header: "Snappy Plays the Stock Market",
      content: "Auntie Pip recommended that he should look into investing in companies with increasing sales over the last few years. Rabbit’s Clean Water Company, for example, had made a very good profit last year and Skunk’s Perfume Company was slowly earning a little more each year, as his perfumes became more popular.",
      imageUrl: "",
      funFact: "Why do investors look for companies that show steady growth over time?",
    },
    {
      book: 3,
      title: "Snappy Plays the Stock Market",
      tagline: "Snappy loses some and wins some",
      id: 33,
      header: "Snappy Plays the Stock Market",
      content: "Snappy wasn’t sure, however, in which company to invest.  He didn’t know much about perfumes and was a little concerned that Skunk was a somewhat unsavory character. Rabbit’s company was doing pretty well, but Snappy didn’t quite understand how the water was made cleaner by Rabbit’s special process.",
      imageUrl: "",
      funFact: "Why is understanding a company’s business and values important when deciding where to invest?",
    },
    {
      book: 3,
      title: "Snappy Plays the Stock Market",
      tagline: "Snappy loses some and wins some",
      id: 34,
      header: "Snappy Plays the Stock Market",
      content: "“Don’t invest in a company just because you like its product or its founder,” recommended Auntie Pip. “Let’s look at companies that make more profit each year and that pay back some nuts, or ‘dividends’, to its investors each year. And we should look at companies that don’t cost too many nuts to buy their stocks.”",
      imageUrl: "",
      funFact: "Why is it important to focus on financial facts, like profits and dividends, instead of personal preferences when investing?",
    },
    {
      book: 3,
      title: "Snappy Plays the Stock Market",
      tagline: "Snappy loses some and wins some",
      id: 35,
      header: "Snappy Plays the Stock Market",
      content: "So Snappy started doing some research. The Deer Brothers’ Lawn Service had increased profits, called earnings, each year for three years and paid dividends each year, but now it cost twenty nuts to buy a stock. That seemed too expensive to Snappy.",
      imageUrl: "",
      funFact: "How can the price of a stock affect whether it’s a good investment or not?",
    },
    {
      book: 3,
      title: "Snappy Plays the Stock Market",
      tagline: "Snappy loses some and wins some",
      id: 36,
      header: "Snappy Plays the Stock Market",
      content: "Auntie asked if the Lawn Service company was likely to increase sales enough next year to justify the high price, but Snappy thought they were already working on as many lawns as they could take care of.",
      imageUrl: "",
      funFact: "Why should investors think about a company’s future growth potential before buying its stock?",
    },
    {
      book: 3,
      title: "Snappy Plays the Stock Market",
      tagline: "Snappy loses some and wins some",
      id: 37,
      header: "Snappy Plays the Stock Market",
      content: "Rabbit's Clean water had earned profits last year, but not the two earlier years, so Snappy decided not to buy them either.",
      imageUrl: "",
      funFact: "Why is it better to invest in companies that have a consistent track record of profits?",
    },
    {
      book: 3,
      title: "Snappy Plays the Stock Market",
      tagline: "Snappy loses some and wins some",
      id: 38,
      header: "Snappy Plays the Stock Market",
      content: "Skunk's Perfumes had smooth earnings growth and regular dividends, and only cost ten nuts worth of stocks for one nut of profit paid out in dividends, so Snappy decided to buy some of that company.",
      imageUrl: "",
      funFact: "Why do investors prefer companies with steady growth, regular dividends, and affordable stock prices?",
    },
    {
      book: 3,
      title: "Snappy Plays the Stock Market",
      tagline: "Snappy loses some and wins some",
      id: 39,
      header: "Snappy Plays the Stock Market",
      content: "Both Skunk and Snappy were happy. Skunk was happy to have more capital to create more interesting perfume combinations, and Snappy was happy to invest in a profitable enterprise. Even though he thought the perfumes smelled terrible, Snappy was pleased with his investment and its earnings.",
      imageUrl: "",
      funFact: "How can focusing on financial performance, rather than personal opinions, lead to smart investment decisions?",
    },
    {
      book: 4,
      title: "Snappy Loses",
      tagline: "A risky investment",
      id: 40,
      header: "Snappy Loses",
      content: "Snappy is enthusiastic about his shares in Skunk’s Perfume Company, and is starting to appreciate the varied scents that Skunk produces. Once you get used to them, they aren’t so bad!",
      imageUrl: "4/0.png",
      funFact: "Why might it be a good idea to keep an open mind about your investments, even if they’re not what you expected at first?",
    },
    {
      book: 4,
      title: "Snappy Loses",
      tagline: "A risky investment",
      id: 41,
      header: "Snappy Loses",
      content: "Snappy noticed that Owl installed a sign above his bank’s door that displays the stock prices of the various forest businesses. A group of field mice are kept busy changing the sign frequently as the stocks’ value goes up and down.",      
      imageUrl: "",
      funFact: "Why do stock prices change so often, and what does this tell us about the stock market?",
    },
    {
      book: 4,
      title: "Snappy Loses",
      tagline: "A risky investment",
      id: 42,
      header: "Snappy Loses",
      content: "Noticing the stock price for Skunk’s Perfume Company listed as going up, Snappy thinks that maybe he should sell some of his shares in the company and take a profit from this price increase.",      
      imageUrl: "",
      funFact: "Why might selling a stock when its price is high be a good way to make a profit?",
    },
    {
      book: 4,
      title: "Snappy Loses",
      tagline: "A risky investment",
      id: 43,
      header: "Snappy Loses",
      content: "Once he sees how much profit he made from selling the shares, he realizes how fun it is to get more nuts without working for them.",      
      imageUrl: "",
      funFact: "How can investing help you earn money without needing to work for it directly?",
    },
    {
      book: 4,
      title: "Snappy Loses",
      tagline: "A risky investment",
      id: 44,
      header: "Snappy Loses",
      content: "Then, Snappy notices that the price of shares has gone down, so he decides to buy more shares. A few days later, he sees that the price has gone up again, so he sells again and gets more profits. What fun this is!",      
      imageUrl: "",
      funFact: "What is the advantage of buying stocks when their prices are low and selling them when their prices are high?",
    },
    {
      book: 4,
      title: "Snappy Loses",
      tagline: "A risky investment",
      id: 45,
      header: "Snappy Loses",
      content: "Snappy begins to watch the stock ticker sign all day, and buys and sells as the price moves down and up.  But one day the stock price drops and doesn't come back up at all.",      
      imageUrl: "",
      funFact: "What are the risks of focusing only on short-term stock price changes?",
    },
    {
      book: 4,
      title: "Snappy Loses",
      tagline: "A risky investment",
      id: 46,
      header: "Snappy Loses",
      content: "Snappy realizes that trading all day, called “day trading”, of course, only works when the market is going up.",      
      imageUrl: "",
      funFact: "Why might relying on day trading be risky if the market doesn’t always go up?",
    },
    {
      book: 4,
      title: "Snappy Loses",
      tagline: "A risky investment",
      id: 47,
      header: "Snappy Loses",
      content: "Then Snappy is told by Owl that he must pay a few seeds to Owl each time he buys or sells a stock.  This is called a “trading commission” and he learns that a substantial part of his profits actually goes to pay the commission.",      
      imageUrl: "",
      funFact: "How do trading commissions reduce the profits you make from frequent buying and selling of stocks?",
    },
    {
      book: 4,
      title: "Snappy Loses",
      tagline: "A risky investment",
      id: 48,
      header: "Snappy Loses",
      content: "Snappy is discouraged at seeing almost all his profits lost by paying this commission. He is upset at himself for having spent so much time concentrating on one stock’s ups and downs.",      
      imageUrl: "",
      funFact: "Why is it important to consider the costs and time involved in managing your investments?",
    },
    {
      book: 4,
      title: "Snappy Loses",
      tagline: "A risky investment",
      id: 49,
      header: "Snappy Loses",
      content: "Maybe it would be smarter not to spend all his time and nuts buying just one stock.  Maybe he should look at a combination of stocks.",      
      imageUrl: "",
      funFact: "Why might it be safer to invest in a mix of different stocks instead of focusing on just one?",
    },
    {
      book: 5,
      title: "Snappy Buys a Bond",
      tagline: "A safer way to invest",
      id: 50,
      header: "Snappy Buys a Bond",
      content: "Snappy has learned that profiting from quickly buying and selling stocks is not a good business plan.  In fact, he lost a lot of money in his last ‘day trading’ adventure!",
      imageUrl: "5/0.png",
      funFact: "Why is it important to avoid risky strategies like day trading if you want to protect your money?",
    },
    {
      book: 5,
      title: "Snappy Buys a Bond",
      tagline: "A safer way to invest",
      id: 51,
      header: "Snappy Buys a Bond",
      content: "A talkative blue jay told him that Bear, who runs the forest, was running out of revenue which he normally got from taxes paid by the forest business people and homeowners. He wanted to borrow some money from the forest citizens and promised to pay it back with interest.",
      imageUrl: "",
      funFact: "Why might governments or leaders borrow money from citizens, and how does paying interest encourage people to lend?",
    },
    {
      book: 5,
      title: "Snappy Buys a Bond",
      tagline: "A safer way to invest",
      id: 52,
      header: "Snappy Buys a Bond",
      content: "Snappy wanted a safer, more regular income and was willing to lend some money to Bear. Or perhaps he could find another company that offers a similarly safe investment. Which should he choose?",
      imageUrl: "",
      funFact: "Why might someone prefer a safer investment, even if it doesn’t earn as much money as riskier options?",
    },
    {
      book: 5,
      title: "Snappy Buys a Bond",
      tagline: "A safer way to invest",
      id: 53,
      header: "Snappy Buys a Bond",
      content: "Lending to someone else is called 'buying a bond' from them because they are required to pay it back. For each nut Snappy lent, the business or Bear must pay a few seeds, called ‘interest’, and eventually return a nut to Snappy.",
      imageUrl: "",
      funFact: "How does lending money through bonds work, and why do lenders earn interest?",
    },
    {
      book: 5,
      title: "Snappy Buys a Bond",
      tagline: "A safer way to invest",
      id: 54,
      header: "Snappy Buys a Bond",
      content: "Bonds from a business, Snappy learned, are called ‘corporate bonds.’ Bonds from Bear are called ‘Treasury Bonds’.",
      imageUrl: "",
      funFact: "What’s the difference between corporate bonds and treasury bonds, and why might people choose one over the other?",
    },
    {
      book: 5,
      title: "Snappy Buys a Bond",
      tagline: "A safer way to invest",
      id: 55,
      header: "Snappy Buys a Bond",
      content: "Snappy could get a consistent payout of seeds from this type of lending. Bear will pay either a few seeds per month, or Snappy could wait until the end of the year to collect, and get a larger payout of seeds.",
      imageUrl: "",
      funFact: "Why might some people prefer to receive smaller, regular payments instead of waiting for a larger payment at the end of the year?",
    },
    {
      book: 5,
      title: "Snappy Buys a Bond",
      tagline: "A safer way to invest",
      id: 56,
      header: "Snappy Buys a Bond",
      content: "Other businesses in the forest paid seeds for bonds as well. For example, Mrs. Mole owned an underground storage business that never made much money, but is a safe investment and has never had problems. Mrs. Mole wanted to expand her storage area, and offered Corporate Bonds - for one acorn, she will pay two sesame seeds and return the acorn at the end of the year.",
      imageUrl: "",
      funFact: "Why might investing in a business with a steady but small profit still be a good choice for some people?",
    },
    {
      book: 5,
      title: "Snappy Buys a Bond",
      tagline: "A safer way to invest",
      id: 57,
      header: "Snappy Buys a Bond",
      content: "Bear encouraged the business owners in the forest to offer bonds and citizens to buy them, so he does not collect taxes on this transaction.",
      imageUrl: "",
      funFact: "How does offering bonds benefit both businesses and citizens, and why might it be tax-free?",
    },
    {
      book: 5,
      title: "Snappy Buys a Bond",
      tagline: "A safer way to invest",
      id: 58,
      header: "Snappy Buys a Bond",
      content: "Bear himself needed to start a major construction of a bridge over a creek, and offered Treasury Bonds to pay the Beaver engineers to construct it. He will give three sesame seeds for an acorn if he is allowed to keep the acorn an entire year.",
      imageUrl: "",
      funFact: "How do government projects like bridges benefit from bonds, and why might they offer higher interest to attract investors?",
    },
    {
      book: 5,
      title: "Snappy Buys a Bond",
      tagline: "A safer way to invest",
      id: 59,
      header: "Snappy Buys a Bond",
      content: "Snappy decided that he will buy some Treasury Bonds from Bear as it was a very safe investment. Bear was powerful enough to get all the nuts and seeds he needed, so Snappy trusted him to honor the agreement. Big Bear will not ‘default’ on the year-end payment, so Snappy knows he is lending wisely.",
      imageUrl: "",
      funFact: "Why is it important to trust that the borrower can pay back the money before you invest in bonds?",
    },
    {
      book: 6,
      title: "Snappy and the Mutual Fund",
      tagline: "Investing in a group",
      id: 60,
      header: "Snappy and the Mutual Fund",
      content: "Snappy has learned that the price of the shares of one company can rise and fall, but thinks that if business is good in the forest, most stock prices should go up.",
      imageUrl: "6/0.png",
      funFact: "Why might the overall economy affect the performance of most companies in the stock market?",
    },
    {
      book: 6,
      title: "Snappy and the Mutual Fund",
      tagline: "Investing in a group",
      id: 61,
      header: "Snappy and the Mutual Fund",
      content: "He talked to Owl, owner of Owl’s Bank, and learned that he could buy a share in several companies at once.",
      imageUrl: "",
      funFact: "How does investing in multiple companies at once reduce the risk of losing money?",
    },
    {
      book: 6,
      title: "Snappy and the Mutual Fund",
      tagline: "Investing in a group",
      id: 62,
      header: "Snappy and the Mutual Fund",
      content: "Owl had bought some of almost every stock available in the forest and created a pool of these shares.",
      imageUrl: "",
      funFact: "What is the benefit of pooling stocks from different companies into one investment?",
    },
    {
      book: 6,
      title: "Snappy and the Mutual Fund",
      tagline: "Investing in a group",
      id: 63,
      header: "Snappy and the Mutual Fund",
      content: "Owl offered to sell Snappy a share in the whole pool, which Owl called a ‘Mutual Fund’.",
      imageUrl: "",
      funFact: "What is a mutual fund, and why might it be a good choice for beginner investors?",
    },
    {
      book: 6,
      title: "Snappy and the Mutual Fund",
      tagline: "Investing in a group",
      id: 64,
      header: "Snappy and the Mutual Fund",
      content: "Owl explained that even if the profit from the whole fund is less than the profit from one well-performing stock, there is less chance that the fund price will go down due to a stock’s sales going down.",
      imageUrl: "",
      funFact: "Why is it sometimes better to aim for consistent, steady returns instead of higher, riskier profits?",
    },
    {
      book: 6,
      title: "Snappy and the Mutual Fund",
      tagline: "Investing in a group",
      id: 65,
      header: "Snappy and the Mutual Fund",
      content: "Owl explained a bit more. There are funds representing the whole market, that is, every company in the forest. These are called ‘index funds’ because they include a complete listing, or ‘index’, of the market.",
      imageUrl: "",
      funFact: "What are index funds, and how do they reflect the overall performance of the market?",
    },
    {
      book: 6,
      title: "Snappy and the Mutual Fund",
      tagline: "Investing in a group",
      id: 66,
      header: "Snappy and the Mutual Fund",
      content: "Another type of fund represents only some types of companies. For example, the ‘Engineering Sector’ of funds included Beaver’s Dam-building Company and Otter’s Mudslide Play-Spaces.",
      imageUrl: "",
      funFact: "How do sector-specific funds focus on certain industries, and why might someone choose to invest in them?",
    },
    {
      book: 6,
      title: "Snappy and the Mutual Fund",
      tagline: "Investing in a group",
      id: 67,
      header: "Snappy and the Mutual Fund",
      content: "The ‘Excavation Sector’ type of funds included Mrs. Mole’s Underground Storage company, Earthworm’s Casing Casting Company, and Gopher’s Lawn-Aeration Co-op.",
      imageUrl: "",
      funFact: "What are the risks and benefits of investing in a specific sector instead of the whole market?",
    },
    {
      book: 6,
      title: "Snappy and the Mutual Fund",
      tagline: "Investing in a group",
      id: 68,
      header: "Snappy and the Mutual Fund",
      content: "These specialty funds, while appealing, seemed a little more specialized than an index fund. Which one should Snappy buy?",
      imageUrl: "",
      funFact: "Why might a more diversified option, like an index fund, be safer than a specialized fund?",
    },
    {
      book: 6,
      title: "Snappy and the Mutual Fund",
      tagline: "Investing in a group",
      id: 69,
      header: "Snappy and the Mutual Fund",
      content: "Snappy was willing to accept a little less profit to reduce the chance of a loss, and decided to buy some of Owl’s Index Mutual Fund.",
      imageUrl: "",
      funFact: "Why is reducing the risk of loss an important factor in deciding where to invest your money?",
    },
    {
      book: 7,
      title: "Snappy and Inflation",
      tagline: "Too few nuts",
      id: 70,
      header: "Snappy and Inflation",
      content: "Snappy had been really busy during the Fall season. He had gathered lots of acorns and had stored them safely in Owl’s Bank.",
      imageUrl: "7/0.png",
      funFact: "Why is it important to save resources or money for future needs?",
    },
    {
      book: 7,
      title: "Snappy and Inflation",
      tagline: "Too few nuts",
      id: 71,
      header: "Snappy and Inflation",
      content: "But Snappy had hunted everywhere for his favorite pine cones with tasty pine nuts inside without finding many for winter.",
      imageUrl: "",
      funFact: "How does scarcity of certain goods affect their value in the market?",
    },
    {
      book: 7,
      title: "Snappy and Inflation",
      tagline: "Too few nuts",
      id: 72,
      header: "Snappy and Inflation",
      content: "Last year, he could trade five acorns for a big pine cone, but this year, there were so many acorns on the ground that every animal had plenty.",
      imageUrl: "",
      funFact: "Why might an abundance of something make it less valuable in trade?",
    },
    {
      book: 7,
      title: "Snappy and Inflation",
      tagline: "Too few nuts",
      id: 73,
      header: "Snappy and Inflation",
      content: "Some greedy chipmunks quickly started offering six acorns for one pine cone.",
      imageUrl: "",
      funFact: "How does competition among buyers drive prices higher in the market?",
    },
    {
      book: 7,
      title: "Snappy and Inflation",
      tagline: "Too few nuts",
      id: 74,
      header: "Snappy and Inflation",
      content: "Soon the animals who had pine cones wouldn’t sell for fewer than six or even seven acorns.",
      imageUrl: "",
      funFact: "Why do sellers increase their prices when demand for an item is high and supply is limited?",
    },
    {
      book: 7,
      title: "Snappy and Inflation",
      tagline: "Too few nuts",
      id: 75,
      header: "Snappy and Inflation",
      content: "Snappy was discouraged by this trend, because next year there might not be as many acorns on the ground. If he traded too many this year, he would have to work harder next year to replenish his stores.",
      imageUrl: "",
      funFact: "Why is it important to plan for the future when deciding how much to spend or trade today?",
    },
    {
      book: 7,
      title: "Snappy and Inflation",
      tagline: "Too few nuts",
      id: 76,
      header: "Snappy and Inflation",
      content: "Even worse, he had many acorns collected and was ready to trade them for the pine cones he craved, but the price of pine cones was going up and up.",
      imageUrl: "",
      funFact: "How does inflation make it harder for people to buy the things they want, even if they’ve saved money?",
    },
    {
      book: 7,
      title: "Snappy and Inflation",
      tagline: "Too few nuts",
      id: 77,
      header: "Snappy and Inflation",
      content: "Snappy was worried that he would either go hungry this winter or learn how to eat acorns, which he didn’t much like.",
      imageUrl: "",
      funFact: "Why might inflation force people to make difficult choices about what they can afford?",
    },
    {
      book: 7,
      title: "Snappy and Inflation",
      tagline: "Too few nuts",
      id: 78,
      header: "Snappy and Inflation",
      content: "Snappy now understood that when everyone has lots of acorns, the major forest currency, each acorn can buy or be traded for less than before.",
      imageUrl: "",
      funFact: "How does inflation reduce the value of money or resources when there’s too much of it in circulation?",
    },
    {
      book: 7,
      title: "Snappy and Inflation",
      tagline: "Too few nuts",
      id: 79,
      header: "Snappy and Inflation",
      content: "This is called ‘inflation’ and is a drag on an economy or marketplace.",
      imageUrl: "",
      funFact: "Why is inflation considered harmful to an economy, and how does it affect buyers and sellers?",
    },
    {
      book: 8,
      title: "Snappy's Business",
      tagline: "An innovation!",
      id: 80,
      header: "Snappy's Business",
      content: "Snappy figured out a clever way to collect nuts faster than searching for them on the ground. He put little buckets on the ground under the oak trees and let the acorns fall into them from the tree. Then he simply emptied the buckets to collect the nuts.",
      imageUrl: "8/0.png",
      funFact: "Why is it important to come up with an efficient system when running a business?",
    },
    {
      book: 8,
      title: "Snappy's Business",
      tagline: "An innovation!",
      id: 81,
      header: "Snappy's Business",
      content: "Snappy decided that this system would be valuable to other squirrels so he arranged to sell the buckets to his friends. He called his business “Snappy Bucket Solutions” (SBS).",
      imageUrl: "",
      funFact: "How can identifying a need or problem in the market lead to a successful business idea?",
    },
    {
      book: 8,
      title: "Snappy's Business",
      tagline: "An innovation!",
      id: 82,
      header: "Snappy's Business",
      content: "Since his business had a high ‘overhead’ cost - Snappy must buy the buckets from Duck’s Bucketworks and he must pay for advertising by the Jay News Service, the service was sold at a relatively high price.",
      imageUrl: "",
      funFact: "What is overhead, and why does it increase the cost of running a business?",
    },
    {
      book: 8,
      title: "Snappy's Business",
      tagline: "An innovation!",
      id: 83,
      header: "Snappy's Business",
      content: "In addition, Snappy had to buy a business license from Bear and pay tax on his profits. This was part of the cost of doing business in the forest.",
      imageUrl: "",
      funFact: "Why is it important for businesses to pay taxes and obtain licenses, and what benefits do these steps provide to society?",
    },
    {
      book: 8,
      title: "Snappy's Business",
      tagline: "An innovation!",
      id: 84,
      header: "Snappy's Business",
      content: "Furthermore, Snappy found that raccoon thieves tried to steal the buckets if he wasn’t watching, so he had to hire armed porcupines as guards.",
      imageUrl: "",
      funFact: "How does hiring security or taking protective measures increase a business’s costs?",
    },
    {
      book: 8,
      title: "Snappy's Business",
      tagline: "An innovation!",
      id: 85,
      header: "Snappy's Business",
      content: "All these precautions cost money. Snappy was glad that he saved so many acorns and invested them wisely. Still, he realized that he needed to take out a loan, or borrow, from Owl’s Bank to fund the first purchase of buckets for resale.",
      imageUrl: "",
      funFact: "Why might a business need to take out a loan, and how can loans help a business grow?",
    },
    {
      book: 8,
      title: "Snappy's Business",
      tagline: "An innovation!",
      id: 86,
      header: "Snappy's Business",
      content: "Snappy calculated that his business’s profits would justify the cost of the loan from Owl, who charged fees for the ability to borrow from the bank.",
      imageUrl: "",
      funFact: "Why is it important for a business to calculate whether it can repay a loan before borrowing money?",
    },
    {
      book: 8,
      title: "Snappy's Business",
      tagline: "An innovation!",
      id: 87,
      header: "Snappy's Business",
      content: "No sooner had Snappy signed the papers to get the loan, he learned that the chipmunk clan had opened a business very similar to SBS. The Chipmunk’s Bucket Solution system, or CBS, was made of paper sacks and cost less than SBS’s sturdy buckets.",
      imageUrl: "",
      funFact: "How does competition affect a business, and why might a new competitor lower prices or offer different products?",
    },
    {
      book: 8,
      title: "Snappy's Business",
      tagline: "An innovation!",
      id: 88,
      header: "Snappy's Business",
      content: "Snappy was very upset by this competition. He released an ad that explained how his solution was better than the Chipmunks’ and lowered his prices a little, but his sales began to decline. What to do?",
      imageUrl: "",
      funFact: "What strategies can businesses use to handle competition, and why is it important to stay flexible?",
    },
    {
      book: 8,
      title: "Snappy's Business",
      tagline: "An innovation!",
      id: 89,
      header: "Snappy's Business",
      content: "Finally, Snappy sat down with the Chipmunks. After long talks with the greedy clan, the two parties came to a good solution: Snappy would buy the Chipmunks’ business. Everyone was happy - the Chipmunks were wealthy and Snappy owned the entire nut collection sector of business in the forest.",
      imageUrl: "",
      funFact: "How can buying out a competitor be a good solution to competition, and what are the benefits for both parties?",
    },
    {
      book: 9,
      title: "Snappy Buys His Nest",
      tagline: "A homeowner at last",
      id: 90,
      header: "Snappy Buys His Nest",
      content: "Snappy was a prosperous squirrel now, with a successful business providing nut-collecting solutions to the forest citizens and  a solid investment portfolio. Finally he could start looking for a new place to live!",
      imageUrl: "9/0.png",
      funFact: "How can having a successful business and investments help provide financial security and open up new opportunities?",
    },
    {
      book: 9,
      title: "Snappy Buys His Nest",
      tagline: "A homeowner at last",
      id: 91,
      header: "Snappy Buys His Nest",
      content: "At first, he thought it would be cheaper to rent, rather than buy his own nest. But when he looked around his neighborhood, the only nests for rent cost more in monthly rental money than he thought was reasonable.",
      imageUrl: "",
      funFact: "What are the pros and cons of renting versus buying a home, and how can renting sometimes end up being more expensive in the long run?",
    },
    {
      book: 9,
      title: "Snappy Buys His Nest",
      tagline: "A homeowner at last",
      id: 92,
      header: "Snappy Buys His Nest",
      content: "Snappy decided to consult Weasel’s Real Estate company to see a choice of nests to buy. Weasel was happy to show him what was available.",
      imageUrl: "",
      funFact: "How can consulting with a professional help when making an important financial decision like buying a home?",
    },
    {
      book: 9,
      title: "Snappy Buys His Nest",
      tagline: "A homeowner at last",
      id: 93,
      header: "Snappy Buys His Nest",
      content: "The first nest Weasel showed Snappy was very fancy, very large and high in a big elm tree with great views. But it cost more nuts than Snappy had.",
      imageUrl: "",
      funFact: "Why is it important to live within your budget when making large purchases, such as buying a home?",
    },
    {
      book: 9,
      title: "Snappy Buys His Nest",
      tagline: "A homeowner at last",
      id: 94,
      header: "Snappy Buys His Nest",
      content: "Weasel assured Snappy that he could borrow most of the cost of the nest and that he wouldn’t have to pay for the whole nest all at once. Weasel could even loan Snappy most of the money.",
      imageUrl: "",
      funFact: "What are the benefits and risks of borrowing money (taking out a loan) when buying a big purchase like a home?",
    },
    {
      book: 9,
      title: "Snappy Buys His Nest",
      tagline: "A homeowner at last",
      id: 95,
      header: "Snappy Buys His Nest",
      content: "Snappy knew, however, that Weasel charged many nuts as payment for the loan and that he would have to work very hard next year to pay back Weasel due to the high rate of interest he charged. Snappy thought this nest was too expensive for his budget and asked to see something else.",
      imageUrl: "",
      funFact: "How can interest on a loan increase the total cost of purchasing something, and why is it important to consider the long-term costs before borrowing money?",
    },
    {
      book: 9,
      title: "Snappy Buys His Nest",
      tagline: "A homeowner at last",
      id: 96,
      header: "Snappy Buys His Nest",
      content: "The next nest Weasel showed Snappy was a run-down, small nest only a few feet off the ground. “You can fix it up in no time!” said Weasel, “and it’s very cheap!” Snappy didn’t want to spend a lot of time and money on a fixer-upper nest, so he said, “No, thanks.”",
      imageUrl: "",
      funFact: "Why is it important to consider not just the upfront cost of a home, but also the potential cost of repairs and maintenance?",
    },
    {
      book: 9,
      title: "Snappy Buys His Nest",
      tagline: "A homeowner at last",
      id: 97,
      header: "Snappy Buys His Nest",
      content: "Finally, Weasel showed Snappy the perfect nest. It was medium sized, halfway up an oak tree. It was big enough and had acorns right on the tree for Snappy to gather and invest. Snappy happily said, “I’ll take it!”",
      imageUrl: "",
      funFact: "How can buying a home that meets your needs and fits your budget provide stability and peace of mind?",
    },
    {
      book: 9,
      title: "Snappy Buys His Nest",
      tagline: "A homeowner at last",
      id: 98,
      header: "Snappy Buys His Nest",
      content: "Buying property was a serious step for Snappy. He had to sign many papers. He had to agree to pay for the nest and any repairs it might need if damaged or even blown out of the tree in a storm. This is called ‘insurance.’",
      imageUrl: "",
      funFact: "Why is it important to have insurance to protect your home and other valuable assets from unexpected damage or loss?",
    },
    {
      book: 9,
      title: "Snappy Buys His Nest",
      tagline: "A homeowner at last",
      id: 99,
      header: "Snappy Buys His Nest",
      content: "Finally, he was ready to move in! His new neighbors, Robin and a family of Cardinals, brought him housewarming presents. His Auntie Pip brought him a big cake which he shared with his neighbors. Finally, Snappy has a home!",
      imageUrl: "",
      funFact: "How can buying a home lead to new opportunities and a sense of stability for the future?",
    },
    {
      book: 10,
      title: "Snappy Plans for the Future",
      tagline: "A comfortable future",
      id: 100,
      header: "Snappy Plans for the Future",
      content: "Inside his cozy new nest, Snappy leaned back and thought about his plans for the future. His finances were well-managed now.",
      imageUrl: "10/0.png",
      funFact: "How can managing your finances effectively help you feel more secure and confident about the future?",
    },
    {
      book: 10,
      title: "Snappy Plans for the Future",
      tagline: "A comfortable future",
      id: 101,
      header: "Snappy Plans for the Future",
      content: "He had some of his property safe in Owl’s Bank, earning steady interest.",
      imageUrl: "",
      funFact: "What is interest, and how can earning interest on savings help grow your money over time?",
    },
    {
      book: 10,
      title: "Snappy Plans for the Future",
      tagline: "A comfortable future",
      id: 102,
      header: "Snappy Plans for the Future",
      content: "He had a little of his property invested in individual companies, including Skunk’s Perfumes and the Deer Brothers’ Lawn Service. The stock he had bought in these companies returned dividends regularly.",
      imageUrl: "",
      funFact: "What are dividends, and how can investing in stocks that pay dividends provide a regular income?",
    },
    {
      book: 10,
      title: "Snappy Plans for the Future",
      tagline: "A comfortable future",
      id: 103,
      header: "Snappy Plans for the Future",
      content: "More of his income was invested in the mutual funds created by Owl: a general index fund that included many of the forest businesses and a fund from the Engineering Sector that included Beaver’s and Mole’s businesses.",
      imageUrl: "",
      funFact: "What is a mutual fund, and how does it allow you to invest in multiple companies at once to reduce risk?",
    },
    {
      book: 10,
      title: "Snappy Plans for the Future",
      tagline: "A comfortable future",
      id: 104,
      header: "Snappy Plans for the Future",
      content: "To balance these riskier investments, Snappy also had bought bonds from Bear which were very safe and guaranteed to return some dividends.",
      imageUrl: "",
      funFact: "What are bonds, and why are they considered a safer investment compared to stocks?",
    },
    {
      book: 10,
      title: "Snappy Plans for the Future",
      tagline: "A comfortable future",
      id: 105,
      header: "Snappy Plans for the Future",
      content: "Now a homeowner and entrepreneur with a solid investment portfolio, Snappy started to think about his future expenses and how to budget for them.",
      imageUrl: "",
      funFact: "Why is it important to plan and budget for future expenses, especially for things like family, education, and retirement?",
    },
    {
      book: 10,
      title: "Snappy Plans for the Future",
      tagline: "A comfortable future",
      id: 106,
      header: "Snappy Plans for the Future",
      content: "Maybe he might meet a nice squirrel lady, get married, and have a family. Educating young squirrels was expensive. While a family is young, he should invest in more aggressive mutual funds and stocks to build his savings quickly.",
      imageUrl: "",
      funFact: "How can life changes, like starting a family, affect your financial goals, and why might you want to invest more aggressively when you are young?",
    },
    {
      book: 10,
      title: "Snappy Plans for the Future",
      tagline: "A comfortable future",
      id: 107,
      header: "Snappy Plans for the Future",
      content: "Then, later on, he might want to buy a small nest in the warmer South, sell his business, and retire. Once he no longer earned an income, he could reorganize his portfolio to include less risky investments.",
      imageUrl: "",
      funFact: "How can your investment strategy change as you approach retirement, and why is it important to shift to safer investments as you get older?",
    },
    {
      book: 10,
      title: "Snappy Plans for the Future",
      tagline: "A comfortable future",
      id: 108,
      header: "Snappy Plans for the Future",
      content: "For the time being, Snappy will keep investing aggressively while he is young. He will mostly invest in mutual funds and a few individual stocks and buy more bonds as he got older.",
      imageUrl: "",
      funFact: "Why is it important to adjust your investment approach over time based on your age, income, and risk tolerance?",
    },
    {
      book: 10,
      title: "Snappy Plans for the Future",
      tagline: "A comfortable future",
      id: 109,
      header: "Snappy Plans for the Future",
      content: "But for now, Snappy was thrilled to be a business owner and homeowner with a solid financial outlook for the future!",
      imageUrl: "",
      funFact: "How can achieving financial stability through smart investments and managing your business help you feel secure and excited about the future?",
    }

  ];
  
  export const getStoriesByBook = (bookNumber: number): Story[] => {
    return stories.filter(story => story.book === bookNumber);
  };
  
  // Get first story from each unique book
export const getFirstStoryPerBook = (stories: Story[]): Story[] => {
  const bookMap = new Map<number, Story>();
  
  stories.forEach(story => {
    if (!bookMap.has(story.book)) {
      bookMap.set(story.book, story);
    }
  });

  return Array.from(bookMap.values());
};